### ISSUE TITLE
Go-barber-UserRepository-Problem

### ISSUE THREAD

**Issue by luminuszz** [japaaak/GoBarber-server#2]
[@japaaak](url)  , Bom dia meu amigo , Sou Davi lá no fórum 

 ` public async save(user: User): Promise<User> {
    await this.ormRepository.save(user);
  }
`

Perceba que você apenas salva o parametro user, antes de salva-lo você precisa cirar a instancia do objeto com o método create dessa forma:

`
const { email, password, name } = user;

    const newUser = this.ormRepository.create({
      email,
      password,
      name,
    });

    await this.ormRepository.save(newUser);

    return newUser;

[Forum](https://app.rocketseat.com.br/h/forum/bootcamp/555faf2d-e0ed-40b6-8449-f999f98922a2)

**Comment by japaaak** [comment]
@luminuszz Bom dia, Davi!
Coloquei o código aqui e deu certo! 

Obrigado mesmo!!!

**Comment by luminuszz** [comment]
![image](https://user-images.githubusercontent.com/48535259/91780721-c474ca00-ebce-11ea-83a9-efe33558692e.png)
